## Problem Statement

Q.1 Write a function to compute 5/0 and use try/except to catch the exceptions.

In [0]:
def divide(numerator, denominator):
  try:
    return numerator / denominator
  except ZeroDivisionError as error:
    return "Cannot divide by zero"

print(divide(5,0))


Cannot divide by zero


Q.2 Implement a Python program to generate all sentences where subject is in ["Americans",
"Indians"] and verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"].

    Hint: Subject,Verb and Object should be declared in the program as shown below.
    subjects=["Americans ","Indians"]
    verbs=["play","watch"]
    objects=["Baseball","Cricket"]

    Output should come as below:
    Americans play Baseball.
    Americans play Cricket.
    Americans watch Baseball.
    Americans watch Cricket.
    Indians play Baseball.
    Indians play Cricket.
    Indians watch Baseball.
    Indians watch Cricket.

In [0]:
subjects=["Americans ","Indians"]
verbs=["play","watch"]
objects=["Baseball","Cricket"]
sentences = [s + " " + v + " " + o for s in subjects for v in verbs for o in objects]
for sentance in sentences:
  print(sentance)

Americans  play Baseball
Americans  play Cricket
Americans  watch Baseball
Americans  watch Cricket
Indians play Baseball
Indians play Cricket
Indians watch Baseball
Indians watch Cricket


Q.3 Write a function so that the columns of the output matrix are powers of the input vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.

    HINT: Such a matrix with a geometric progression in each row is named for Alexandre Theophile Vandermonde.

In [0]:
import numpy as np

def vendermonde(x, n):
  return np.vander(x, n)

x = np.array([1, 2, 3, 5])
n = 4

print(vendermonde(x, n))


[[  1   1   1   1]
 [  8   4   2   1]
 [ 27   9   3   1]
 [125  25   5   1]]
